### PR TITLE
Set descriptions for every state in ALM  

### LINKED ISSUE #396: Provide description for every state a particular bridge relay request
Consider to add description for every state tracked by the AMB Live monitor for the requiested transaction.

### State transitioning: Foreign->Home

**State**: 0
**Status**: Error
**Message to the user**: Transaction not found. 1. Check that the transaction hash is correct. 2. Wait several blocks for the transaction to be mined, gas price effects mining speed.
**Design note**: The transaction specified by the user not found.

**State**: 1
**Status**: Waiting
**Message to the user**: The specified transaction was included in a block. Validators are waiting for chain finalization before sending their confirmations.
**Design note**: The transaction specified by the user was included in a block but no transactions from any validator were found

**State**: 2
**Status**: Waiting
**Message to the user**: The specified transaction was included in a block. Some validators have sent confirmations, others are waiting for chain finalization.
**Design note**: The transaction specified by the user was included in a block but less than “requiredSignatures” of validators sent the transactions with confirmation

**State**: 3
**Status**: Pending
**Message to the user**: The specified transaction was included in a block. A majority of validators sent confirmations which have not yet been added to a block. 
**Design note**: ”requiredSignatures” or more validators sent confirmations but most of them were not mined yet

**State**: 4
**Status**: Failed
**Message to the user**: The specified transaction was included in a block, but confirmations sent by a majority of validators failed. The cross-chain relay request will not be processed. Contact to the validators by messaging on https://forum.poa.network/c/support.
**Design note**: The number of failed confirmations does not allow to reach required number of the signatures 

**State**: 5
**Status**: Success
**Message to the user**: ---
**Design note**: Confirmations of ”requiredSignatures” or more validators were successfully included into blocks

### State transitioning: Home->Foreign 

**State**: 0
**Status**: Error
**Message to the user**: Transaction not found. 1. Check that the transaction hash is correct. 2. Wait several blocks for the transaction to be mined, gas price effects mining speed.
**Design note**: The transaction specified by the user not found.

**State**: 1
**Status**: Confirmation waiting
**Message to the user**: The specified transaction was included in a block. Validators are waiting for chain finalization before sending their signatures.
**Design note**: The transaction specified by the user was included in a block but no transactions from any validator were found in the Home chain

**State**: 2
**Status**: Confirmation waiting
**Message to the user**: The specified transaction was included in a block. Some validators have sent signatures, others are waiting for chain finalization.
**Design note**: The transaction specified by the user was included in a block but less than “requiredSignatures” of validators sent the transactions with confirmation

**State**: 3
**Status**: Confirmation pending
**Message to the user**: The specified transaction was included in a block. A majority of validators sent signatures which have not yet been added to a block. 
**Design note**: ”requiredSignatures” or more validators sent confirmations but most of them were not mined yet

**State**: 4
**Status**: Confirmation failed
**Message to the user**: The specified transaction was included in a block, but transactions with signatures sent by a majority of validators failed. The cross-chain relay request will not be processed. Contact to the validators by messaging on https://forum.poa.network/c/support.
**Design note**: The number of failed confirmations does not allow to reach required number of the signatures 

**State**: 5
**Status**: Execution waiting
**Message to the user**: The specified transaction was included in a block and the validators collected signatures. Either 1. One of the validators is waiting for chain finalization. 2. A validator skipped its duty to relay signatures. Check status again after a few blocks. If the issue still persists contact to the validators by messaging on https://forum.poa.network/c/support.
**Design note**: Signatures were collected in the Home chain but the transaction from the validator to forward signatures was not found on the Foreign side.

**State**: 6
**Status**: Execution pending
**Message to the user**: The specified transaction was included in a block and the validators collected signatures. The validator’s transaction with collected signatures was sent but is not yet added to a block.
**Design note**: The transaction from the validator to forward signatures was discovered in the transaction pool on the Foreign side but not mined yet.

**State**: 7
**Status**: Execution failed
**Message to the user**: The specified transaction was included in a block and the validators collected signatures. The validator’s transaction with collected signatures was sent but did not succeed. Contact to the validators by messaging on https://forum.poa.network/c/support.
**Design note**: The transaction with collected signatures was included in the block on the Foreign side but its status is “failed”.

**State**: 8
**Status**: Success
**Message to the user**: ---
**Design note**: The transaction with the collected signatures was applied successfully to the Foreign chain. It does not matter if it is sent by a validator or by another account.

### PR DESCRIPTION
**Pull request by patitonar**
Closes #396 

Demo updated: https://alm-demo-e0998.web.app/

### CODE REVIEW

File: alm/src/config/descriptions.ts [hunk 1]
```diff
@@ -9,29 +9,58 @@ export const TRANSACTION_STATUS_DESCRIPTION: { [key: string]: string } = {
...
+  WAITING_VALIDATORS: 'Confirmation Waiting',
+  WAITING_CHAIN: 'Confirmation Waiting'
 }
 
-// %homeChain will be replaced by the home network name
-// %foreignChain will be replaced by the foreign network name
+// use %link to identify a link
 export const CONFIRMATIONS_STATUS_DESCRIPTION: { [key: string]: string } = {
   SUCCESS: '',
   SUCCESS_MESSAGE_FAILED:
```
Comment (patitonar) [inline alm/src/config/descriptions.ts:35]: The scenario `SUCCESS_MESSAGE_FAILED` was not covered in the descriptions provided. Please check the text I added for this case

File: alm/src/config/descriptions.ts [hunk 2]
```diff
@@ -9,29 +9,58 @@ export const TRANSACTION_STATUS_DESCRIPTION: { [key: string]: string } = {
...
+    'The specified transaction was included in a block.\nSome validators have sent confirmations, others are\nwaiting for chain finalization.',
+  WAITING_CHAIN:
+    'The specified transaction was included in a block.\nValidators are waiting for chain finalization before\nsending their confirmations.'
+}
+
+// use %link to identify a link
+export const CONFIRMATIONS_STATUS_DESCRIPTION_HOME: { [key: string]: string } = {
+  SUCCESS: '',
+  SUCCESS_MESSAGE_FAILED:
+    'The specified transaction was included in a block,\nthe validators collected signatures and the cross-chain relay was executed correctly,\nbut the contained message execution failed.',
```
Comment (akolotov) [inline alm/src/config/descriptions.ts:51]:
```suggestion
    'The specified transaction was included in a block,\nthe validators collected signatures and the cross-chain relay was executed correctly,\nbut the contained message execution failed.\nContact the support of the application you used to produce the transaction for the clarifications.',
```
