### PR TITLE
Fix flaky UI-E2E

### LINKED ISSUE #73: UI-E2E tests flakiness
Turns out that the `ui-e2e` tests are flaky.

#### Failing run
- [CircleCI build 836](https://circleci.com/gh/poanetwork/tokenbridge/836)
- Output from `yarn run ui-e2e`: [failing-836.txt](https://github.com/poanetwork/tokenbridge/files/3219393/failing-836.txt)
Screenshot 2019-05-25 at 15 00 34

- There is a `this.retries(2)` which means that the tests were run 3 times in total
  - The output from mocha does not show 3 attempts, only last one but the tests are tried 3 times as I confirmed on the side with `console.logs`

#### Successful run
- [CircleCI build 842](https://circleci.com/gh/poanetwork/tokenbridge/842)
- Output from `yarn run ui-e2e`: [passing-842.txt](https://github.com/poanetwork/tokenbridge/files/3219395/passing-842.txt)
- **Same commit as the failing run** - just hit re-run on CI

I didn't find any meaningful differences in the outputs and I don't know what might be the cause of this.

### PR DESCRIPTION
**Pull request by rzadp**
I suspect #73 is caused by the block-generation script which uses the same private key as the UI user, and sometimes the transaction is replaced.

I have run the `ui-e2e` job multiple times:
- one run: https://circleci.com/workflow-run/de160c13-ae61-4e42-a851-e9a5a23de13a
- another run: https://circleci.com/workflow-run/17f80937-b24b-482b-ba74-ee0c7caf8126

and it looks like it closes #73

I have also changed the interval to 1s to speed up `ui-e2e` a little bit.

### CODE REVIEW

File: e2e-commons/scripts/blocks.js [hunk 1]
```diff
@@ -3,18 +3,36 @@ const { generateNewBlock } = require('../utils')
...
-    generateNewBlock(homeWeb3, user.address)
-    generateNewBlock(foreignWeb3, user.address)
+    generateNewBlock(homeWeb3, blockGenerator.address)
+    generateNewBlock(foreignWeb3, blockGenerator.address)
     main()
-  }, 5000)
+  }, 1000)
 }
 
+homeWeb3.eth.sendTransaction({
```
Comment (akolotov) [inline e2e-commons/scripts/blocks.js]: Instead of performing transaction you can add the account to the genesis files: [chain.json](https://github.com/poanetwork/tokenbridge/blob/speed-ui-e2e/parity/chain.json) and [chain-foreign.json](https://github.com/poanetwork/tokenbridge/blob/speed-ui-e2e/parity/chain-foreign.json)

Comment (rzadp) [reply e2e-commons/scripts/blocks.js]: Right. Done.
