### PR TITLE
Fix monitor metrics

### LINKED ISSUE #517: Unclaimed txs are not covered in prometheus metrics for erc20-to-native contracts
Here is the current state of json's metrics and prometheus metrics prepared by the monitor for the xDai bridge:

```json
{
  "home":{
    "totalSupply":"5837495.351403181175737791",
    "deposits":13116,
    "withdrawals":30907
  },
  "foreign":{
    "erc20Balance":"5867418.920003181175737791",
    "deposits":12773,
    "withdrawals":30907
  },
  "balanceDiff":"0",
  "lastChecked":1614376455,
  "depositsDiff":0,
  "withdrawalDiff":0,
  "unclaimedDiff":343,
  "unclaimedBalance":"29923.5686",
  "health":true,
  "timeDiff":182
}
```

```
balances_home_value 5835816.351403181
balances_home_txs_deposit 13117
balances_home_txs_withdrawal 30908
balances_foreign_value 5865739.920003181
balances_foreign_txs_deposit 12774
balances_foreign_txs_withdrawal 30908
balances_diff_value 0
balances_diff_deposit 0
balances_diff_withdrawal 0
```

As it is shown the information about unclaimed transfers is missed in the prometheus metrics.
Consider to add:
```
balances_unclaimed_txs X
balances_unclaimed_value X
```

### LINKED ISSUE #518: Prometheus metrics does not allow detect the amb contracts imbalance.
These are examples of the outputs the monitor produces for the json's version of metrics and for the prometheus metrics:

```json
{
  "home":{
    "toForeign":6004,
    "fromForeign":53584
  },
  "foreign":{
    "fromHome":5908,
    "toHome":53585
  },
  "lastChecked":1614377833,
  "fromHomeToForeignDiff":6,
  "fromHomeToForeignPBUDiff":90,
  "fromForeignToHomeDiff":-1,
  "health":true,
  "timeDiff":23
}
```

```
balances_home_value 0
balances_home_txs_deposit 0
balances_home_txs_withdrawal 0
balances_foreign_value 0
balances_foreign_txs_deposit 0
balances_foreign_txs_withdrawal 0
balances_diff_value 0
balances_diff_deposit 0
balances_diff_withdrawal 0
```

Obviously the information about messages passed through the bridge in different direction is missed. 
Consider to use the following mapping to produce the prometheus metrics:
```
home:toForeign --> txs_home_out
home:fromForeign --> txs_home_in
foreign:toHome --> txs_foreign_out
foreign:fromHome --> txs_foreign_in
fromHomeToForeignDiff --> txs_diff_home_out_oracles
fromHomeToForeignPBUDiff --> txs_diff_home_out_users
fromForeignToHomeDiff --> txs_diff_foreign_out
```

### LINKED ISSUE #519: Output balances only of requested validators in prometheus metrics
Since there are options to configure the monitor to track the balance only for requested validators:

Example for the xDai bridge:
```
MONITOR_HOME_VALIDATORS_BALANCE_ENABLE=0x9ad83402C19Af24F76afa1930a2B2EEC2F47A8C5
MONITOR_FOREIGN_VALIDATORS_BALANCE_ENABLE=0x9ad83402C19Af24F76afa1930a2B2EEC2F47A8C5
```

Consider to output the balances of validators listed in `MONITOR*_VALIDATORS_BALANCE_ENABLE` only.

So, 
```
validators_balances_home0{address="0x9ad83402C19Af24F76afa1930a2B2EEC2F47A8C5"} 0.0974415085
validators_balances_home1{address="0x4D1c96B9A49C4469A0b720a22b74b034EDdFe051"} 0
validators_balances_home2{address="0x491FC792e78CDadd7D31446Bb7bDDef876a69AD6"} 0
validators_balances_home3{address="0xc073C8E5ED9Aa11CF6776C69b3e13b259Ba9F506"} 0
validators_balances_home4{address="0xfe24Cfb2F8872e9ed097C451dE065A9F6048915b"} 0
validators_balances_foreign0{address="0xfe24Cfb2F8872e9ed097C451dE065A9F6048915b"} 0
validators_balances_foreign1{address="0x9ad83402C19Af24F76afa1930a2B2EEC2F47A8C5"} 6.612599150560642
validators_balances_foreign2{address="0x4D1c96B9A49C4469A0b720a22b74b034EDdFe051"} 0
validators_balances_foreign3{address="0x491FC792e78CDadd7D31446Bb7bDDef876a69AD6"} 0
validators_balances_foreign4{address="0xc073C8E5ED9Aa11CF6776C69b3e13b259Ba9F506"} 0
```
will be shortened to
```
validators_balances_home0{address="0x9ad83402C19Af24F76afa1930a2B2EEC2F47A8C5"} 0.0974415085
validators_balances_foreign0{address="0x9ad83402C19Af24F76afa1930a2B2EEC2F47A8C5"} 6.612599150560642
```
It is OK if the index of the same validator (if there are more than one validator in `MONITOR*_VALIDATORS_BALANCE_ENABLE`) in the list could be different from time to time since we are mostly interested in the balance value rather than exact validator address.

### LINKED ISSUE #520: Block ranges info in prometheus metrics
Consider to modify the monitor behavior as so the prometheus metrics could contain the info about the block ranges which the monitor collected the data from:
```
state_startblock_home
state_startblock_foreign
state_endblock_home
state_endblock_foreign
```
- `state_startblock_*` must be taken from the monitor config
- `state_endblock_*` must reflect the latest block the monitor picked from the chain to filter out the events and get the contracts/balances state on.

### PR DESCRIPTION
**Pull request by LyzeOfKiel**
Closes #517
Closes #518
Closes #519
Closes #520

Now metrics are collected via the `metricsWorker` in the background (previously they were assembled on the fly). Added handling of AMB metrics. Also, I decided to include information about the last home/foreign block in the `alerts.json` file (`metricsWorker` retrieves this info later). I think this way information about misbehaviour ranges will be more clear.

### CODE REVIEW

**Comment by k1rill-fedoseev** [comment]
Seems that metrics worker will fail for non-AMB bridge. This is due to the lack of `failures.json` file. Failures are only checked out for AMB bridge.
I have got the following error:
```Error: ENOENT: no such file or directory, open './responses/xdai/failures.json'```

**Comment by LyzeOfKiel** [comment]
> Seems that metrics worker will fail for non-AMB bridge. This is due to the lack of `failures.json` file. Failures are only checked out for AMB bridge.
> I have got the following error:
> `Error: ENOENT: no such file or directory, open './responses/xdai/failures.json'`

This is log of error caught  by `readFile`: https://github.com/poanetwork/tokenbridge/blob/f93ab330cc8bae9230fbe6c2a9268027989be256/monitor/utils/file.js#L10-L14
If some JSON response file is not present, metrics worker will just skip it

File: monitor/alerts.js [hunk 1]
```diff
@@ -59,6 +58,8 @@ async function main() {
       mostRecentTxHash: xAffirmationsMostRecentTxHash,
       transactions: xAffirmationsTxs
     },
+    homeBlockNumber,
```
Comment (akolotov) [inline monitor/alerts.js:61]: Consider to publish the info about the block range in `getBalances.json`. It is entry point to the monitoring stats so it will be useful to see the block range here.

**Review by akolotov — CHANGES_REQUESTED** [review]

File: monitor/alerts.js (hunk 1 above)
Comment (LyzeOfKiel) [reply monitor/alerts.js]: Agree, done

**Review by k1rill-fedoseev — APPROVED** [review]
